name: Docs

on: [push, pull_request]

jobs:

  DocLint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: anishathalye/proof-html@3cb0083534425b4902e6e77ac26ac3fe5b718f51 # v2.2.4
        with:
          directory: ./docs
          check_favicon: false
          enforce_https: false
          url_ignore: |
            http://www.fabricadigital.com.br
            http://www.saxproject.org/
          url_ignore_re: |
            ^http://files.luaforge.net/
            ^https://opensource.org/
            ^https://www.cvedetails.com/vulnerability-list.php
