name: Docs

on: [push, pull_request]

jobs:

  DocLint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: anishathalye/proof-html@de0745a75f536af1360d37849a8a732413fad66b # v1
        with:
          directory: ./docs
          check_favicon: false
          enforce_https: false
          url_ignore: |
            http://www.fabricadigital.com.br
            http://www.saxproject.org/
          url_ignore_re: |
            ^http://files.luaforge.net/
            ^https://opensource.org/
            ^https://www.cvedetails.com/vulnerability-list.php
